spring:
 datasource:
   url: jdbc:h2:file:~/filrouge2
   
 jpa:    
  hibernate:
   ddl-auto: update
# spring data jpa
 # jpa:
    #hibernate:
     # ddl-auto: create ou update
      
 #   show-sql: true

#spring:
 # datasource:
  #  url: jdbc:postgresql://localhost:5432/Gestion
   # username: postgres
    #password: 

  #jpa:
  
management:
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true      
      

  endpoints:
    web:
      exposure:
        exclude: "env,beans"
        include: "*"
    enabled-by-default: true

server:
  servlet:
    context-path: /projetfilrouge
   